### ISSUE TITLE
Error: 'onPhoneShake' is not defined.

### ISSUE THREAD

**Issue by albercode10** [folksable/shake_detector#2]
Error: 'onPhoneShake' is not defined; 'onShake' is used instead. 

Please update the documentation to reflect this change. Additionally, if possible, update the example documentation on pub.dev to reflect the usage of 'onShake' instead of 'onPhoneShake'.

Thank in advance.

**Comment by drxddy** [comment]
Thanks for informing.
Updated docs with new release [v0.1.2](https://pub.dev/packages/shake_detector/versions/0.1.2)
